image: Visual Studio 2017

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

environment:
  nodejs_version: 8
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0

# Finish on first failed build
matrix:
  fast_finish: true

platform:
  - x64

branches:
  only:
    - master

# Disable Visual Studio build and deploy
build: off
deploy: off

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - yarn install

test_script:
  - node --version
  - yarn lint
  - ps: |
      $action={write-host "[$(Get-Date)]PID = $($Event.SourceEventArgs.NewEvent.processid)"; write-host "[$(Get-Date)] Process = $($Event.SourceEventArgs.NewEvent.ProcessName)"}
      $query = "Select * from win32_ProcessStartTrace where processname = *"
      Register-CimIndicationEvent -Query $query -SourceIdentifier "ProcessMemory" -Action $action
  - yarn flow-ci
  #- ps:  Get-WMIObject Win32_Process | Select Name,@{n="Private Memory(mb)";e={$_.PrivatePageCount/1mb}}
  - yarn build
  - yarn test
  - yarn prettier

#cache:
 #- node_modules
 #- "%LOCALAPPDATA%/Yarn"
